### ISSUE TITLE
Datasource name is missed from the UI

### ISSUE THREAD

**Issue by b-slim** [yahoo/swiv#4]
Datasource name is missed from the UI. 
![swiv](https://cloud.githubusercontent.com/assets/7376396/22355457/84993d9e-e3df-11e6-91a6-6b2fb4730c3b.png)

although i can see it on the console.
```shell
Introspecting all sources in cluster 'druid'
Scanning cluster 'druid' for new sources
Got the latest time for 'basefact_network' (2014-11-01T00:00:00.000Z)
Got the latest time for 'druid_tpcds_ss_sold_time_2' (1999-09-16T00:00:00.000Z)
Got the latest time for 'druid_tpcds_ss_sold_time_subset' (1999-11-30T00:00:00.000Z)
Got the latest time for 'druid_hive_table' (2016-06-01T02:00:00.000Z)
Got the latest time for 'druid_tpcds_ss_sold_time' (2003-01-02T00:00:00.000Z)
```

**Comment by pjain1** [comment]
yeah that seems to be the current behavior as it does not auto generate data cube name but if you use config.yaml file generated either manually or through swiv using `swiv --druid your.druid.broker.host:8082 --print-config --with-comments > config.yaml` then the names will show up.
